# Generated by Django 3.1.7 on 2021-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210401_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='published_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='postunlike',
            name='published_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
